services:
  db:
    container_name: local-sql-db
    image: mcr.microsoft.com/mssql/server:2019-CU28-ubuntu-20.04
    platform: "linux/amd64"
    environment:
      - MSSQL_SA_PASSWORD=Password123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
