// <auto-generated />
using FeatureFlagsEfDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeatureFlagsEfDemo.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeatureFlagsEfDemo.Features.FeatureFlags.FeatureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Feature", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Subtract"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HandleDivideByZeroRequests"
                        });
                });

            modelBuilder.Entity("FeatureFlagsEfDemo.Features.FeatureFlags.FeatureEntity", b =>
                {
                    b.OwnsOne("FeatureFlagsEfDemo.Features.FeatureFlags.FeatureEntity.FeatureDetail#FeatureFlagsEfDemo.Features.FeatureFlags.FeatureDetailEntity", "FeatureDetail", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("bit");

                            b1.HasKey("Id");

                            b1.ToTable("FeatureDetail", (string)null);

                            b1.WithOwner("Feature")
                                .HasForeignKey("Id");

                            b1.Navigation("Feature");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    IsEnabled = false
                                },
                                new
                                {
                                    Id = 2,
                                    IsEnabled = false
                                });
                        });

                    b.Navigation("FeatureDetail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
